### ISSUE TITLE
Not support IDA 7.0 

### ISSUE THREAD

**Issue by JsHuang** [iphelix/ida-sploiter#6]
I got errors with ida-sploiter when using it in IDA Version 7.0.170914 Windows x64.
```
Failed while executing plugin_t.init():
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/idasploiter.py", line 2700, in init
    if idasploiter_manager.add_menu_items():
  File "C:/Program Files/IDA 7.0/plugins/idasploiter.py", line 2601, in add_menu_items
    if self.add_menu_item_helper("View/Open subviews/Segments", "Modules", "Shift+F6", 0, self.show_modules_view, None): return 1
  File "C:/Program Files/IDA 7.0/plugins/idasploiter.py", line 2593, in add_menu_item_helper
    addmenu_item_ctx = idaapi.add_menu_item(menupath, name, hotkey, flags, pyfunc, args)
AttributeError: 'module' object has no attribute 'add_menu_item'
```
It seems the idaapi.add_menu_item is not supported in the new IDA version

**Comment by apogiatzis** [comment]
Same issue here

Edit: I have created a temporary fix and open a PR. But for now,  you can use that one https://github.com/apogiatzis/ida-sploiter/tree/support-ida7

**Comment by JsHuang** [comment]
@apogiatzis Thanks for your fix, but it  still has errors:
```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] 
IDAPython v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/idasploiter.py", line 2597, in activate
    pyfunc()
  File "C:/Program Files/IDA 7.0/plugins/idasploiter.py", line 2654, in show_rop_view
    self.sploiter.process_rop()
  File "C:/Program Files/IDA 7.0/plugins\idasploiter.py", line 873, in process_rop
    f = RopForm(self, select_list)
  File "C:/Program Files/IDA 7.0/plugins\idasploiter.py", line 1246, in __init__
    'cEChooser'       : Form.EmbeddedChooserControl(self.mod, swidth=131),
  File "C:\Program Files\IDA 7.0\python\ida_kernwin.py", line 4219, in __init__
    raise ValueError("Invalid chooser passed.")
ValueError: Invalid chooser passed.
```

**Comment by apogiatzis** [comment]
Ah yeah I know where this comes from. Give me some days and I will draft a fix

**Comment by hdbreaker** [comment]
Hi guys, do you have a fix for this?

**Comment by int3rsys** [comment]
> 
> 
> Hi guys, do you have a fix for this?



> 
> 
> Same issue here
> 
> Edit: I have created a temporary fix and open a PR. But for now, you can use that one https://github.com/apogiatzis/ida-sploiter/tree/support-ida7

Thanks. It resolved the error that pops when starting IDA, but it won't let me search for gadgets.
